name: staph-salt-rnaseq

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - fastqc
  - multiqc
  - sra-tools
  - trimmomatic=0.39
  - hisat2
  - samtools
  - subread
  - wget
  - openjdk
  - r-base
  - r-tidyverse
  - r-pheatmap
  - bioconductor-deseq2
  - bioconductor-rtracklayer
  - bioconductor-enhancedvolcano

